exports.config={
  "exchange":"Kucoin",
  "apiKey":"",
  "apiSecret":"",
  "port":800,
  "globalTickDelay":30000,
  "strategies":[
    {
      "name":"CentaurusContinues",
      "symbols":["ALGO-USDT"],
      "inputs":null
    }
  ]
};
